export const searchDemoItems = [
  {
    id: 'start',
    label: 'Getting started',
    description: 'Set up your first project',
    group: 'Documentation',
    meta: 'Guide',
    keywords: ['setup', 'onboarding'],
  },
  {
    id: 'auth',
    label: 'Authentication',
    description: 'Connect your application securely',
    group: 'Documentation',
    meta: 'API',
    keywords: ['token', 'login'],
  },
  {
    id: 'search',
    label: 'Search API',
    description: 'Query and rank results',
    group: 'Documentation',
    meta: 'API',
    keywords: ['query', 'filter'],
  },
  {
    id: 'hooks',
    label: 'Webhooks',
    description: 'Receive event notifications',
    group: 'Documentation',
    meta: 'API',
    keywords: ['events'],
  },
  {
    id: 'import',
    label: 'Import data',
    description: 'Upload a CSV file',
    group: 'Documentation',
    meta: 'Guide',
    keywords: ['migration'],
  },
  {
    id: 'release',
    label: 'Release notes',
    description: 'Recent improvements',
    group: 'Updates',
    meta: 'Article',
    keywords: ['changes'],
  },
]
